### ISSUE TITLE
Consider options for new directory structure [need discussion]

### ISSUE THREAD

**Issue by abierbaum** [trestle-pm/trestle#23]
The structure of the files seems a bit off to me still.  I thought we could collect different options to consider in this issue.

**Comment by abierbaum** [comment]
Option 1:

The idea here is to put all the controllers and templates for a common "page" / "panel" / "area" in the same directory.  This has the benefit of making it easier to see the forest through the trees IMHO because everything related to that are is there.

Example:

```
app
  - board
    - board_ctrl.js
    - board_ctrl.spec.js
    - board_routes.js
    - board.tpl.html
    - board.scss
    - issue_columns_ctrl.js
    - issue_columns_ctrl.spec.js
    - issue_collumns.tpl.html
    - issue_ctrl.js
    - issue_ctrl.spec.js
    - issue.tpl.html
```

This really focuses on keeping everything together and trying to keep from having subdirectories all of the place that contain only one piece of code and split things out more than they are needed.  Since everything for the one area of the system is in one directory, it makes it easier to see what all the pieces are and hopefully will focus the developer on where to put everything.

**Comment by abierbaum** [comment]
Option 2:

The idea here is to put all the controllers and specs into a shared file for a given panel/page.

Example:

```
app
  - board
    - board_controllers.js
    - board_controllers.spec.js
    - board_routes.js
    - board.tpl.html
    - board.scss
    - issue_collumns.tpl.html
    - issue.tpl.html
```

The main benefit here is that everything is kept very close together.  In a normal app it looks like controllers are going to be small and there will be a lot of them.  So in this case we simply put them all in the same file to make them easy to reference when coding and keep there from being massive numbers of small files in the source directory.

**Comment by my8bird** [comment]
I think the issue you are going to run into is the gray area of what a page/panel is when deciding how to break the files apart.  

Is the board a panel that shows sub panels (ie. the columns) or are the both proper high level panels?  In both cases would the card be a high level panel or simply a sub panel of one of the higher level ones?

I guess what I am driving at is that controller is a thing in angular and panel is not and I think, very much could be wrong, that it would be less nebulous to break the code apart by angular lines.

As such I would propose these points as the criteria to use when critiquing layout options;
1. Choices are based on angular types (service, directive, filter, controller)
2. Tests are easily findable based on the sources location (either like taccs where we mimic the structure or with specs inline)
3. Easily tell what module needs to be required to use the functionality of a file.
4. Only one module in use per actual file (drives at easily finding the module for a file)
5. Should resemble common angular structures (holy wars could be fought looking up links but the goal is to help a new person to the project, but not angular, get started)

Given that I would propose the following structure:

```
 - src
  - app
   - module.js (defines the module, all files in this folder MUST use the same module)
   - routes.js (defines the routes if there are any)
   - controllers.js (defines all controllers used in this module, could be a lot or a few)
   - services.js
   - filters.js
   - directives.js
   - *.spec.js (one for each js file in the folder)
   - *.tpl.html (template files)
   - /submodule
   - /submodule/module.js (defines the submodule, note that module.js of the parent MUST name 
     this as a requirement so that importing the parent gives access to the children).
```

This is lossely based on the angular seed project and ng-boilerplate.  The filenaming is from seed and highlevel structure from boilerplate.  The `module.js` file comes from a project that I can no longer recall the name of and I think the module.js file could map to us python users as **init**.py pretty well so using that to define the module/package seems good.

All this to bring me to the actual layout this would derive:

```
 - src
   - app
     - board
       - controllers.js ... Other common (per definition above) angular project files
       - login_details/ ... 

- src
  - common
    - github_api
      - services.js
      - services.spec.js
```

Here I have defined that the board is one unit in all regards except the login details which is its own unit of work that can function without any of the board code.  As a result this view could be moved in the future so that the Milestone/Planning mode can use it also.  I have also defined that there is a shared component for the github api that only has services.

One downside of this approach is that we end up with several `controllers.js` files which makes finding the right file in editors difficult.  To work around this, one variation could be to prefix all files in a module with their folders name.  so `src/app/board/controllers.js` would become `src/app/board/board_controllers.js`.  It looks silly in a path like this but does have obvious gains when actually working with the code.
